name: 'Get Netlify deployment URL'
description: 'Get Netlify deployment URL at the current branch'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'main.js'
