name: Log event
on: [check_suite]

jobs:
  build:
    name: Log event job
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Install npm dependencies
        run: npm install

      - name: Set Deploy URL
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        run: node ./actions/set-deploy-url.js

      - name: Run end-to-end tests with Cypress
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        run: CYPRESS_BASE_URL=DEPLOY_URL npm run test:e2e
