name: Audit Netlify Deploy Preview
on:
  check_suite:
    types: [completed]

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        run: npm install --no-optional --no-audit

      - uses: ./.github/actions/get-netlify-url
      # if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'

      - name: Run Cypress
        uses: ./.github/actions/run-cypress

      # cypress run --config baseUrl=http://hi.com/
      # - name: Run end-to-end tests with Cypress
      #   if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
      #   run: CYPRESS_CACHE_FOLDER=$GITHUB_WORKSPACE/cypress-cache; npm run test:e2e
