name: Audit Preview
on: [push, pull_request]

jobs:
  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - uses: voorhoede/get-netlify-url@v1
        id: get-netlify-url
        with:
          basic-auth-username: demo
          basic-auth-password: tryme

      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_BASE_URL: ${{ steps.get-netlify-url.outputs.url }}
        with:
          wait-on: ${{ steps.get-netlify-url.outputs.url }}
