name: Log event
on: [check_suite]

jobs:
  build:
    name: Log event job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
        run: npm install
      - name: Run end-to-end tests with Cypress
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        run: |
          CYPRESS_BASE_URL=https://demo-actions-on-netlify.netlify.com
          npm run test:e2e
