name: Audit Deploy
on:
  check_suite:
    types: [completed]

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        run: npm install --no-optional --no-audit

      - uses: ./.github/actions/get-netlify-url
        id: get-netlify-url
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'

      - name: Run Cypress
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        uses: ./.github/actions/run-cypress
        with:
          base-url: ${{ steps.get-netlify-url.outputs.url }}

  webhint:
    name: Web Hint
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        run: npm install --no-optional --no-audit

      - uses: ./.github/actions/get-netlify-url
        id: get-netlify-url
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'

      - name: Run Web Hint
        if: github.event.check_suite.app.name == 'Netlify' && github.event.check_suite.conclusion == 'success'
        run: npm run test:hint -- ${NETLIFY_URL}
        env:
          NETLIFY_URL: ${{ steps.get-netlify-url.outputs.url }}
