name: Log event
on: [check_suite, push]

jobs:
  build:
    name: Log event job
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v1
      - name: Log event step
        run: node ./.github/actions/log-event/log-event.js
